CREATE TABLE STUDENT (
    student_id NUMBER PRIMARY KEY,
    name VARCHAR2(50),
    age NUMBER,
    course VARCHAR2(50),
    marks NUMBER
);

INSERT INTO STUDENT VALUES (1, 'Ayush', 21, 'CSE', 90);
INSERT INTO STUDENT VALUES (2, 'Sneha', 20, 'IT', 82);
INSERT INTO STUDENT VALUES (3, 'Vikram', 22, 'ECE', 75);
INSERT INTO STUDENT VALUES (4, 'Kavya', 19, 'ME', 95);
INSERT INTO STUDENT VALUES (5, 'Rahul', 21, 'CSE', 68);

COMMIT;


SELECT * FROM STUDENT;
SELECT name, marks FROM STUDENT;

SELECT * FROM STUDENT
WHERE marks > 80;
